### ISSUE TITLE
$20 (white) is being mapped to$10 (grey)

### ISSUE THREAD

**Issue by mhughson** [clbr/neslib#3]
https://github.com/clbr/neslib/blob/d061b0f7f1a449941111c31eee0fc2e85b1826d7/neslib.sinc#L1232

I don't understand why this was done. It seems intentional, but I can't figure out what it's trying to do. The comment says:

> ;$10 because $20 is the same as $30

**Comment by mhughson** [comment]
I think I understand the intent here now.

The library is asking artists to NOT use $20, and instead use $30 as they are the same visually.

As a result, the fade code can behave a little nicer, by skipping passed $20 to $10 (grey) so that the fade is instant.

**Comment by clbr** [comment]
That's correct. Closing.
